---
git:
  depth: false
language: cpp
sudo: required

services:
  - docker

before_install:
  - git submodule update --init --recursive
  - docker pull hootenanny/rpmbuild-hoot-release@sha256:d41955e2b2b7bff973a23f289e373fb2c8117339b97fbefe2244c9e295b93f10
  - |
    mkdir -p -m 0755 $HOME/{.m2,.npm,SOURCES}
    curl -sSL https://s3.amazonaws.com/hoot-maven/m2-cache.tar.gz | tar -C $HOME/.m2 -xzf -
    sudo chown -R 1000:1000 $HOME/{.m2,.npm,SOURCES} .

install: true

script:
  - |
    docker run \
      -v $HOME/SOURCES:/rpmbuild/SOURCES:rw \
      -v $HOME/.m2:/rpmbuild/.m2:rw \
      -v $HOME/.npm:/rpmbuild/.npm:rw \
      -v $TRAVIS_BUILD_DIR:/rpmbuild/hootenanny:rw \
      -it --rm \
      hootenanny/rpmbuild-hoot-release@sha256:d41955e2b2b7bff973a23f289e373fb2c8117339b97fbefe2244c9e295b93f10 \
      /rpmbuild/hootenanny/scripts/ci/archive.sh
