---
language: cpp
sudo: required

services:
  - docker

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install curl
  - docker pull hootenanny/rpmbuild-hoot-release:git065b4f
  - git submodule update --init --recursive
  - mkdir -m 0755 $HOME/{.m2,.npm,scripts,SOURCES}
  - curl -sSL -o $HOME/scripts/hoot-archive.sh https://raw.githubusercontent.com/ngageoint/hootenanny-rpms/develop/scripts/hoot-archive.sh

script:
  - docker run \
      -v $HOME/scripts:/rpmbuild/scripts:ro \
      -v $HOME/SOURCES:/rpmbuild/SOURCES:rw \
      -v $HOME/.m2:/rpmbuild/.m2:rw \
      -v $HOME/.npm:/rpmbuild/.npm:rw \
      -v $(pwd):/rpmbuild/hootenanny:rw \
      -it --rm \
      hootenanny/rpmbuild-hoot-release:git065b4f \
      /rpmbuild/scripts/hoot-archive.sh
