---
version: 2

jobs:
  build:
    working_directory: '~/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release:latest
        entrypoint:
          - '/docker-entrypoint.sh'
    steps:
      - checkout
      - run:
          name: 'Download Archive Script'
          command: |
            mkdir -p ~/SOURCES
            curl -sSL -O https://raw.githubusercontent.com/ngageoint/hootenanny-rpms/master/scripts/hoot-archive.sh
  test:
    working_directory: '~/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release:latest
        entrypoint:
          - '/docker-entrypoint.sh'
      - run:
          name: Hello
          command: |
            echo "Hello, World!"

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
