---
version: 2

jobs:
  archive:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release@sha256:d41955e2b2b7bff973a23f289e373fb2c8117339b97fbefe2244c9e295b93f10
    steps:
      - checkout
      - run:
          name: 'Git Submodules'
          command: |
            chown -R rpmbuild:rpmbuild .
            su-exec rpmbuild git submodule update --init --recursive
      - run:
          name: 'Download and Extract Maven Cache'
          command: |
            if [ ! -d /rpmbuild/.m2/repository ]; then
              su-exec rpmbuild bash -c "mkdir -p /rpmbuild/.m2 && curl -sSL https://s3.amazonaws.com/hoot-maven/m2-cache.tar.gz | tar -C /rpmbuild/.m2 -xzf -"
            fi
      - run:
          name: 'Create Archive'
          command: |
            su-exec postgres pg_ctl -D $PGDATA -s start
            su-exec rpmbuild /rpmbuild/hootenanny/scripts/ci/archive.sh
            mkdir -p /tmp/archive
            mv -v /rpmbuild/hootenanny/hootenanny-[0-9]*.tar.gz /tmp/archive
      - store_artifacts:
          path: /tmp/archive
          destination: archives

workflows:
  version: 2
  archive:
    jobs:
      - archive
