---
version: 2

jobs:
  archive:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release:git065b4f9
    steps:
      - checkout
      - run:
          name: 'Git Submodules'
          command: |
            chown -R rpmbuild:rpmbuild .
            su-exec rpmbuild git submodule update --init --recursive
      - run:
          name: 'Download RPM Scripts'
          command: |
            mkdir -m 0755 -p /rpmbuild/{scripts,SPECS}
            chown rpmbuild:rpmbuild /rpmbuild/{scripts,SPECS}
            if [ ! -x /rpmbuild/scripts/hoot-archive.sh ]; then
              cd /rpmbuild/scripts
              su-exec rpmbuild curl -sSL -O https://raw.githubusercontent.com/ngageoint/hootenanny-rpms/develop/scripts/hoot-archive.sh
              chmod +x hoot-archive.sh
            fi
            if [ ! -f /rpmbuild/SPECS/hootenanny.spec ]; then
              cd /rpmbuild/SPECS
              su-exec rpmbuild curl -sSL -O https://raw.githubusercontent.com/ngageoint/hootenanny-rpms/develop/SPECS/hootenanny.spec
            fi
      - run:
          name: 'Download and Extract Maven Cache'
          command: |
            if [ ! -d /rpmbuild/.m2/repository ]; then
              su-exec rpmbuild bash -c "mkdir -p /rpmbuild/.m2 && curl -sSL https://s3.amazonaws.com/hoot-maven/m2-cache.tar.gz | tar -C /rpmbuild/.m2 -xzf -"
            fi
      - run:
          name: 'Create Archive'
          command: |
            su-exec postgres pg_ctl -D $PGDATA -s start
            su-exec rpmbuild /bin/bash -c "export HOOT_HOME=/rpmbuild/hootenanny && cd /rpmbuild/hootenanny/hoot-core && /rpmbuild/hootenanny/scripts/copyright/UpdateAllCopyrightHeaders.sh"

#            mkdir -p /tmp/archive
#            mv -v /rpmbuild/hootenanny/hootenanny-[0-9]*.tar.gz /tmp/archive
#      - store_artifacts:
#          path: /tmp/archive
#          destination: archives

workflows:
  version: 2
  archive:
    jobs:
      - archive
