---
version: 2

jobs:
  build:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release:git065b4f9
        user: rpmbuild
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'
      - restore_cache:
          keys:
            - hoot-archive-v0.2.39
      - run:
          name: 'Download Archive Script'
          command: |
            set -exuo pipefail
            if [ ! -x ~/hoot-archive.sh ]; then cd ~ && curl -sSL -O https://raw.githubusercontent.com/ngageoint/hootenanny-rpms/master/scripts/hoot-archive.sh; fi
      - save_cache:
          key: hoot-archive-v0.2.39
          paths:
            - '~/hoot-archive.sh'
      - restore_cache:
          keys:
            - m2-v0.2.39-hootenanny-{{ .Branch }}
            - m2-v0.2.39-hootenanny-
      - run:
          name: 'Download and Extract Maven Cache'
          command: |
            set -exuo pipefail
            if [ ! -d ~/.m2/repository ]; then mkdir -p ~/.m2 && cd ~/.m2 && curl -sSL https://s3.amazonaws.com/hoot-maven/m2-cache.tar.gz | tar xzf -; fi
      - save_cache:
          key: m2-v0.2.39-hootenanny-{{ .Branch }}
          paths:
            - '~/m2'
  test:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release:git065b4f9
        user: rpmbuild
    steps:
      - run:
          name: Hello
          command: |
            echo "Hello, World!"

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
