---
version: 2

jobs:
  archive:
    working_directory: '/rpmbuild/hootenanny'
    docker:
      - image: hootenanny/rpmbuild-hoot-release:git065b4f9
    steps:
      - checkout
      - run:
          name: 'Git Submodules'
          command: |
            git submodule update --init --recursive
            chown -R rpmbuild:rpmbuild .
      - run:
          name: 'Download RPM Scripts'
          command: |
            set -exuo pipefail
            if [ ! -d /rpmbuild/scripts ]; then mkdir -m 0755 -p /rpmbuild/scripts; fi
            if [ ! -x /rpmbuild/scripts/hoot-archive.sh ]; then cd /rpmbuild/scripts && curl -sSL -O https://raw.githubusercontent.com/ngageoint/hootenanny-rpms/master/scripts/hoot-archive.sh && chmod +x hoot-archive.sh; fi
      - save_cache:
          key: hootenanny-rpms-scripts-v0.2.39
          paths:
            - '/rpmbuild/scripts/hoot-archive.sh'
      - restore_cache:
          keys:
            - hootenanny-m2-v0.2.39-{{ .Branch }}
            - hootenanny-m2-v0.2.39-
      - run:
          name: 'Download and Extract Maven Cache'
          command: |
            set -exuo pipefail
            if [ ! -d /rpmbuild/.m2/repository ]; then mkdir -p /rpmbuild/.m2 && cd /rpmbuild/.m2 && curl -sSL https://s3.amazonaws.com/hoot-maven/m2-cache.tar.gz | tar xzf - && chown -R rpmbuild:rpmbuild /rpmbuild/.m2; fi
      - save_cache:
          key: hootenanny-m2-v0.2.39-{{ .Branch }}
          paths:
            - '/rpmbuild/.m2'
      - run:
          name: Create Archive
          command: |
            set -exuo pipefail
            su-exec postgres pg_ctl -D $PGDATA -s start
            su-exec rpmbuild /rpmbuild/scripts/hoot-archive.sh
            mkdir -p /tmp/archive
            mv -v /rpmbuild/hootenanny/hootenanny-[0-9]*.tar.gz /tmp/archive
      - store_artifacts:
          path: /tmp/archive
          destination: archives

workflows:
  version: 2
  archive:
    jobs:
      - archive
